# Generated by Django 4.2.5 on 2023-10-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentorLixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('geolocalizacao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'contentorerslixo',
                'db_table': 'contentores_lixo',
                'managed': True,
            },
        ),
    ]
