# Generated by Django 5.0 on 2024-01-09 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('ultimo_nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('morada', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Perfis',
                'db_table': 'perfis',
                'managed': True,
            },
        ),
    ]
