# Generated by Django 5.0 on 2024-01-18 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('provincia', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('tipo_material_reciclavel', models.CharField(verbose_name=50)),
                ('descricao', models.CharField(max_length=500)),
                ('quantidade_desejada', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'compradores',
                'db_table': 'comprador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('provincia', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('tipo_material_reciclavel', models.CharField(verbose_name=50)),
                ('quantidade', models.IntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('peso_total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'vendedores',
                'db_table': 'vendedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venda', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlatformReciclagem.comprador')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlatformReciclagem.vendedor')),
            ],
            options={
                'verbose_name_plural': 'vendas',
                'db_table': 'venda',
                'managed': True,
            },
        ),
    ]
