# Generated by Django 5.0 on 2024-01-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentoreslixo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_distancia', models.FloatField(default=0)),
                ('sensor_umidade', models.FloatField(default=0)),
                ('sensor_temperatura', models.FloatField(default=0)),
                ('sensor_chuva', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentoreslixo.contentorlixo')),
            ],
            options={
                'verbose_name_plural': 'dadosensores',
                'db_table': 'dado_sensores',
                'managed': True,
            },
        ),
    ]
