# Generated by Django 4.2.5 on 2023-10-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentoreslixo', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'sensores',
                'db_table': 'sensores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DadoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dado', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentoreslixo.contentorlixo')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor')),
            ],
            options={
                'verbose_name_plural': 'dadosensores',
                'db_table': 'dado_sensores',
                'managed': True,
            },
        ),
    ]
