# Generated by Django 4.2.5 on 2023-11-01 22:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentoreslixo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_ultra_sonico', models.FloatField(default=0)),
                ('sensor_umidade', models.FloatField(default=0)),
                ('sensor_temperatura', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('contentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentoreslixo.contentorlixo')),
            ],
            options={
                'verbose_name_plural': 'dadosensores',
                'db_table': 'dado_sensores',
                'managed': True,
            },
        ),
    ]
