# Generated by Django 4.2.5 on 2023-11-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_alter_dadosensor_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosensor',
            old_name='sensor_ultra_sonico',
            new_name='sensor_distancia',
        ),
        migrations.AddField(
            model_name='dadosensor',
            name='sensor_chuva',
            field=models.BooleanField(default=False),
        ),
    ]
